# Generated by Django 5.1.2 on 2024-10-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="cognome",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="customer",
            name="nome",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="customer",
            name="password",
            field=models.CharField(default="", max_length=50),
        ),
    ]
