# Generated by Django 5.1.2 on 2024-10-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prodotto",
            name="image",
            field=models.ImageField(blank=True, upload_to="uploads/product"),
        ),
    ]
