# Generated by Django 5.1.2 on 2024-10-10 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_customer"),
        ("store", "0003_prodotto_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="account.customer"
            ),
        ),
        migrations.RemoveField(
            model_name="prodotto",
            name="supplier",
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
    ]
