# Generated by Django 5.1.2 on 2024-10-10 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_customer_cognome_alter_customer_email_and_more"),
        ("store", "0004_alter_order_customer_remove_prodotto_supplier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prodotto",
            name="supplier",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.supplier",
            ),
        ),
    ]
