# Generated by Django 5.1.2 on 2024-10-10 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_customer_cognome_alter_customer_email_and_more"),
        ("store", "0005_prodotto_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prodotto",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="account.supplier"
            ),
        ),
    ]
