# Generated by Django 5.1.2 on 2024-10-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_alter_prodotto_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="nome",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="prodotto",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="prodotto",
            name="image",
            field=models.ImageField(
                blank=True,
                default="uploads/product/stock_shoes.jpg",
                upload_to="uploads/product",
            ),
        ),
        migrations.AlterField(
            model_name="prodotto",
            name="nome",
            field=models.CharField(max_length=50),
        ),
    ]
