# Generated by Django 5.1.2 on 2024-10-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_customer_indirizzo"),
        ("store", "0007_alter_category_nome_alter_prodotto_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prodotto",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked", to="account.customer"
            ),
        ),
    ]
