# Generated by Django 5.1.2 on 2024-10-16 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_prodotto_likes"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Order",
        ),
    ]
