# Generated by Django 5.1.2 on 2024-10-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_delete_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="prodotto",
            name="is_sold",
            field=models.BooleanField(default=False),
        ),
    ]
