# Generated by Django 5.1.2 on 2024-11-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_prodotto_is_sold"),
    ]

    operations = [
        migrations.AddField(
            model_name="prodotto",
            name="size",
            field=models.IntegerField(
                choices=[
                    (37, "37"),
                    (38, "38"),
                    (39, "39"),
                    (40, "40"),
                    (41, "41"),
                    (42, "42"),
                    (43, "43"),
                    (44, "44"),
                    (45, "45"),
                ],
                default=37,
            ),
        ),
    ]
