# Generated by Django 5.1.2 on 2024-12-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0014_prodotto_marca"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prodotto",
            name="description",
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
