# Generated by Django 5.1.2 on 2024-10-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0004_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipped_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
