# Generated by Django 5.1.2 on 2024-12-07 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_customer_indirizzo"),
        ("reviews", "0004_alter_review_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="account.supplier",
            ),
        ),
    ]
